begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(61);
create function pg_temp.mid(n int) returns uuid language sql immutable as $$
 select ('f7000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid
$$;
create function pg_temp.claims(n int,s int,extra jsonb default '{}') returns text language sql as $$
 select set_config('request.jwt.claims',(jsonb_build_object('sub',pg_temp.mid(n),'session_id',pg_temp.mid(s),'role','authenticated','aal','aal1')||extra)::text,true)
$$;
insert into auth.users(id,email,is_anonymous) select pg_temp.mid(n),'machine-'||n||'@example.invalid',false from generate_series(1,4) n;
insert into auth.sessions(id,user_id,not_after) select pg_temp.mid(n+100),pg_temp.mid(n),now()+interval '1 hour' from generate_series(1,4) n;
insert into public.organizations(id,name,slug) values(pg_temp.mid(10),'Machine test','machine-test');
insert into public.tenants(id,organization_id,name,slug) values(pg_temp.mid(20),pg_temp.mid(10),'Machine A','machine-a'),(pg_temp.mid(21),pg_temp.mid(10),'Machine B','machine-b');
insert into public.service_identities(id,service_key,name) values(pg_temp.mid(30),'machine-test-service','Machine test');
insert into public.api_clients(id,tenant_id,client_id,name) values(pg_temp.mid(40),pg_temp.mid(20),'machine-test-client','Machine test');
insert into public.service_identity_tenant_grants(service_identity_id,tenant_id,permission_id,scope_json)
 select pg_temp.mid(30),pg_temp.mid(20),id,'{"environment":"sandbox"}' from public.permissions where permission_key in ('integrations.read','security.manage','platform.manage');
insert into public.api_client_permissions(tenant_id,api_client_id,permission_id,condition_json)
 select pg_temp.mid(20),pg_temp.mid(40),id,'{"environment":"sandbox"}' from public.permissions where permission_key='integrations.read';
insert into private.flexexa_machine_principals(id,auth_user_id,principal_type,service_identity_id,environment,valid_from)
 values(pg_temp.mid(50),pg_temp.mid(1),'service',pg_temp.mid(30),'sandbox',now()-interval '1 hour');
insert into private.flexexa_machine_principals(id,auth_user_id,principal_type,tenant_id,api_client_id,environment,valid_from)
 values(pg_temp.mid(51),pg_temp.mid(2),'api_client',pg_temp.mid(20),pg_temp.mid(40),'sandbox',now()-interval '1 hour');

select ok((select relrowsecurity from pg_class where oid='private.flexexa_machine_principals'::regclass),'private bindings have RLS');
select ok(not has_table_privilege('authenticated','private.flexexa_machine_principals','SELECT'),'browser cannot read bindings');
select ok(not has_function_privilege('anon','public.flexexa_machine_has_permission(uuid,text,text)','EXECUTE'),'anonymous cannot invoke wrapper');
select ok(not has_function_privilege('anon','private.flexexa_machine_has_permission(uuid,text,text)','EXECUTE'),'anonymous cannot invoke definer directly');
select ok((select not prosecdef from pg_proc where oid='public.flexexa_machine_has_permission(uuid,text,text)'::regprocedure),'public entrypoint is invoker');
select ok(not exists(select 1 from public.service_identity_tenant_grants where id is null),'canonical service grants have generated stable IDs');
select throws_ok($$insert into private.flexexa_machine_principals(auth_user_id,principal_type,tenant_id,api_client_id,environment) values(pg_temp.mid(3),'api_client',pg_temp.mid(21),pg_temp.mid(40),'sandbox')$$,'23503',null,'client composite FK prevents cross-tenant binding');
select throws_ok($$insert into private.flexexa_machine_principals(auth_user_id,principal_type,environment) values(pg_temp.mid(3),'service','sandbox')$$,'23514',null,'binding requires exact owner type');
select throws_ok($$update private.flexexa_machine_principals set environment='production' where id=pg_temp.mid(50)$$,'23514','MACHINE_PRINCIPAL_IDENTITY_IMMUTABLE','environment identity is immutable');
set local role authenticated;
select pg_temp.claims(1,101,'{}');
select ok(public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'active service grant in explicit sandbox accepted');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(21),'integrations.read','sandbox'),'service cannot access ungranted tenant');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','production'),'sandbox identity cannot use production');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','invalid'),'unknown environment denied');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'unknown.permission','sandbox'),'unknown permission denied');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'platform.manage','sandbox'),'machine has no platform permission shortcut');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'security.manage','sandbox'),'machine cannot satisfy human MFA gate');
select pg_temp.claims(1,101,'{"aal":"aal2"}');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'security.manage','sandbox'),'aal2 claim does not bypass workload assurance gate');
select pg_temp.claims(1,101,'{"is_anonymous":true}');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'anonymous signed identity denied');
select pg_temp.claims(1,101,'{"role":"service_role"}');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'privileged role claim is not machine authentication');
select pg_temp.claims(1,101,'{"session_id":null}');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'missing session denied');
select pg_temp.claims(1,101,'{"session_id":"not-a-uuid"}');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'malformed session denied without unsafe cast');
select pg_temp.claims(1,102,'{}');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'session must belong to authenticated subject');
select pg_temp.claims(3,103,'{"user_metadata":{"service_identity_id":"f7000000-0000-4000-8000-000000000030","environment":"sandbox"}}');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'editable metadata cannot create machine identity');
select pg_temp.claims(1,101,'{}');
select throws_ok($$select * from private.flexexa_machine_principals$$,'42501',null,'private mapping has no browser SELECT');
select throws_ok($$update private.flexexa_machine_principals set status='active'$$,'42501',null,'private mapping has no browser UPDATE');
select throws_ok($$select public.flexexa_register_provider_account(pg_temp.mid(20),'{}','machine-denied',pg_temp.mid(999))$$,'42501','PERMISSION_DENIED','existing human mutation endpoint not opened to machines');
reset role;
update auth.sessions set not_after=now() where id=pg_temp.mid(101);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'expired session denied');
reset role;
update auth.sessions set not_after=now()+interval '1 hour' where id=pg_temp.mid(101);
set local role authenticated;
reset role;
delete from auth.sessions where id=pg_temp.mid(101);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'removed session denies existing bearer claims');
reset role;
insert into auth.sessions(id,user_id) values(pg_temp.mid(101),pg_temp.mid(1));
set local role authenticated;
reset role;
update auth.users set banned_until=now()+interval '1 hour' where id=pg_temp.mid(1);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'banned account denied');
reset role;
update auth.users set banned_until=null where id=pg_temp.mid(1);
set local role authenticated;
reset role;
update auth.users set deleted_at=now() where id=pg_temp.mid(1);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'deleted account denied');
reset role;
update auth.users set deleted_at=null where id=pg_temp.mid(1);
set local role authenticated;
reset role;
update auth.users set is_anonymous=true where id=pg_temp.mid(1);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'database anonymous flag cannot be forged by JWT');
reset role;
update auth.users set is_anonymous=false where id=pg_temp.mid(1);
set local role authenticated;
reset role;
update public.tenants set status='suspended' where id=pg_temp.mid(20);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'suspended tenant denied');
reset role;
update public.tenants set status='active' where id=pg_temp.mid(20);
set local role authenticated;
reset role;
update public.organizations set status='suspended' where id=pg_temp.mid(10);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'suspended organization denied');
reset role;
update public.organizations set status='active' where id=pg_temp.mid(10);
set local role authenticated;
reset role;
update public.service_identities set status='suspended' where id=pg_temp.mid(30);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'suspended service denied');
reset role;
update public.service_identities set status='active' where id=pg_temp.mid(30);
set local role authenticated;
reset role;
update private.flexexa_machine_principals set status='suspended' where id=pg_temp.mid(50);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'suspended binding denied');
reset role;
update private.flexexa_machine_principals set status='active' where id=pg_temp.mid(50);
set local role authenticated;
reset role;
update private.flexexa_machine_principals set valid_until=now() where id=pg_temp.mid(50);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'expired binding denied');
reset role;
update private.flexexa_machine_principals set valid_until=null where id=pg_temp.mid(50);
set local role authenticated;
reset role;
update public.service_identity_tenant_grants set scope_json='{}';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'unscoped grant cannot default to production or sandbox');
reset role;
update public.service_identity_tenant_grants set scope_json='{"environment":"sandbox"}';
set local role authenticated;
reset role;
update public.service_identity_tenant_grants set scope_json='{"environment":"sandbox","asset_id":"unimplemented"}';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'unimplemented grant condition denies rather than widens access');
reset role;
update public.service_identity_tenant_grants set scope_json='{"environment":"sandbox"}';
set local role authenticated;
reset role;
update public.service_identity_tenant_grants set valid_from=now()+interval '1 hour';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'future grant denied');
reset role;
update public.service_identity_tenant_grants set valid_from='-infinity';
set local role authenticated;
reset role;
update public.service_identity_tenant_grants set valid_until=now();
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'grant half-open end enforced');
reset role;
update public.service_identity_tenant_grants set valid_until=null;
set local role authenticated;
reset role;
update public.permissions set requires_step_up=true where permission_key='integrations.read';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'unimplemented step-up fails closed');
reset role;
update public.permissions set requires_step_up=false where permission_key='integrations.read';
set local role authenticated;
reset role;
update public.permissions set status='retired' where permission_key='integrations.read';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'retired permission denied');
reset role;
update public.permissions set status='active' where permission_key='integrations.read';
set local role authenticated;
reset role;
insert into public.service_identity_tenant_grants(service_identity_id,tenant_id,permission_id,scope_json) select pg_temp.mid(30),pg_temp.mid(20),id,'{"environment":"sandbox"}' from public.permissions where permission_key='asset.read';
set local role authenticated;
select ok(public.flexexa_machine_has_permission(pg_temp.mid(20),'assets.read','sandbox'),'legacy grant maps to active canonical permission');
reset role;
update public.permissions set status='retired' where permission_key='asset.read';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'assets.read','sandbox'),'retired alias grant cannot grant active canonical permission');
reset role;
insert into public.memberships(id,tenant_id,user_id) values(pg_temp.mid(60),pg_temp.mid(20),pg_temp.mid(1));
insert into public.membership_roles(tenant_id,membership_id,role_id) select pg_temp.mid(20),pg_temp.mid(60),id from public.roles where tenant_id=pg_temp.mid(20) and role_key='tenant_admin';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'mixed human and machine assignments fail closed');
select ok(not private.flexexa_has_permission(pg_temp.mid(20),'integrations.read'),'machine cannot fall back to human membership');
reset role;
delete from public.memberships where id=pg_temp.mid(60);
insert into public.platform_memberships(id,user_id) values(pg_temp.mid(61),pg_temp.mid(1));
insert into public.platform_membership_roles(platform_membership_id,role_id) select pg_temp.mid(61),id from public.roles where role_key='superadmin' and scope_type='platform';
set local role authenticated;
select pg_temp.claims(1,101,'{"aal":"aal2"}');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'mixed platform and machine assignments denied');
select ok(not private.flexexa_is_platform_admin(),'mapped machine cannot become platform admin');
reset role;
delete from public.platform_memberships where id=pg_temp.mid(61);
set local role authenticated;
select pg_temp.claims(2,102,'{}');
select ok(public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'active scoped API client accepted');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(21),'integrations.read','sandbox'),'API client cannot cross tenant');
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','production'),'API client cannot cross environment');
reset role;
update public.api_clients set status='revoked' where id=pg_temp.mid(40);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'revoked API client denied');
reset role;
update public.api_clients set status='active' where id=pg_temp.mid(40);
set local role authenticated;
reset role;
update public.api_clients set client_type='public' where id=pg_temp.mid(40);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'public browser client cannot act as workload');
reset role;
update public.api_clients set client_type='confidential' where id=pg_temp.mid(40);
set local role authenticated;
reset role;
update public.api_clients set expires_at=now() where id=pg_temp.mid(40);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'expired API client denied');
reset role;
update public.api_clients set expires_at=null where id=pg_temp.mid(40);
set local role authenticated;
reset role;
update public.api_client_permissions set condition_json='{}';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'API client grant must explicitly name environment');
reset role;
update public.api_client_permissions set condition_json='{"environment":"sandbox"}';
set local role authenticated;
reset role;
update public.api_client_permissions set condition_json='{"environment":"sandbox","extra":true}';
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'API client unsupported condition denied');
reset role;
update public.api_client_permissions set condition_json='{"environment":"sandbox"}';
set local role authenticated;
reset role;
update public.api_client_permissions set valid_until=now();
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'expired API client grant denied');
reset role;
update public.api_client_permissions set valid_until=null;
set local role authenticated;
reset role;
update private.flexexa_machine_principals set status='revoked' where id=pg_temp.mid(51);
set local role authenticated;
select ok(not public.flexexa_machine_has_permission(pg_temp.mid(20),'integrations.read','sandbox'),'revoked principal immediately denied on subsequent statement');
reset role;
select throws_ok($$update private.flexexa_machine_principals set status='active' where id=pg_temp.mid(51)$$,'23514','MACHINE_PRINCIPAL_REVOKED','revocation is terminal');
select throws_ok($$delete from private.flexexa_machine_principals where id=pg_temp.mid(51)$$,'23514','MACHINE_PRINCIPAL_DELETE_FORBIDDEN','binding history cannot be erased to restore human fallback');
select ok((select count(*) from public.audit_events where tenant_id in (pg_temp.mid(20),pg_temp.mid(21)))=0 and (select count(*) from public.outbox_events where tenant_id in (pg_temp.mid(20),pg_temp.mid(21)))=0,'preflight does not send commands or fabricate side effects');
select * from finish();
rollback;
