begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create function pg_temp.iid(n integer) returns uuid language sql immutable as $$select ('be140000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table identity_results(name text primary key,body jsonb);
grant all on identity_results to authenticated;
create function pg_temp.claims(n int default 1,s int default 101,extra jsonb default '{}') returns text language sql as $$
 select set_config('request.jwt.claims',(jsonb_build_object('sub',pg_temp.iid(n),'session_id',pg_temp.iid(s),'role','authenticated','aal','aal2')||extra)::text,true)
$$;
create function pg_temp.enroll(p jsonb default '{}',k text default 'enroll-1',c uuid default pg_temp.iid(900)) returns jsonb language sql as $$
 select public.flexexa_enroll_api_client_identity(pg_temp.iid(20),jsonb_build_object('api_client_id',pg_temp.iid(40),'auth_user_id',pg_temp.iid(10),'environment','sandbox')||p,k,c)
$$;
create function pg_temp.revoke(p jsonb default '{}',k text default 'revoke-1',c uuid default pg_temp.iid(901)) returns jsonb language sql as $$
 select public.flexexa_revoke_api_client_identity(pg_temp.iid(20),jsonb_build_object('principal_id',(select body->>'resource_id' from identity_results where name='enroll'),'environment','sandbox','reason_code','security')||p,k,c)
$$;
insert into auth.users(id,email,is_anonymous) select pg_temp.iid(n),'identity-admin-'||n||'@example.invalid',false from generate_series(1,15) n;
insert into auth.sessions(id,user_id,not_after) values(pg_temp.iid(101),pg_temp.iid(1),now()+interval '1 hour'),(pg_temp.iid(102),pg_temp.iid(2),now()+interval '1 hour');
insert into public.organizations(id,name,slug) values(pg_temp.iid(30),'Identity admin','identity-admin');
insert into public.tenants(id,organization_id,name,slug) values(pg_temp.iid(20),pg_temp.iid(30),'Admin A','identity-admin-a'),(pg_temp.iid(21),pg_temp.iid(30),'Admin B','identity-admin-b');
insert into public.memberships(id,tenant_id,user_id) values(pg_temp.iid(31),pg_temp.iid(20),pg_temp.iid(1)),(pg_temp.iid(32),pg_temp.iid(20),pg_temp.iid(2));
insert into public.membership_roles(tenant_id,membership_id,role_id)
 select m.tenant_id,m.id,r.id from public.memberships m join public.roles r on r.tenant_id=m.tenant_id
 where (m.id=pg_temp.iid(31) and r.role_key='tenant_admin') or (m.id=pg_temp.iid(32) and r.role_key='viewer');
insert into public.api_clients(id,tenant_id,client_id,name,expires_at) values(pg_temp.iid(40),pg_temp.iid(20),'enrollment-a','Enrollment A',now()+interval '1 hour'),(pg_temp.iid(41),pg_temp.iid(21),'enrollment-b','Enrollment B',now()+interval '1 hour');
update auth.users set raw_app_meta_data=jsonb_build_object('flexexa_machine_enrollment',jsonb_build_object('version',1,'tenant_id',pg_temp.iid(20),'api_client_id',pg_temp.iid(40),'environment','sandbox')) where id=pg_temp.iid(10);
select ok(not has_function_privilege('anon','public.flexexa_enroll_api_client_identity(uuid,jsonb,text,uuid)','EXECUTE'),'anonymous cannot enroll');
select ok(not has_function_privilege('anon','private.flexexa_administer_api_identity(text,uuid,jsonb,text,uuid)','EXECUTE'),'anonymous cannot use private helper');
select ok(not has_function_privilege('authenticated','private.flexexa_assert_identity_administrator(uuid)','EXECUTE'),'session helper not callable by browser');
select is((select count(*) from pg_proc where oid in('public.flexexa_enroll_api_client_identity(uuid,jsonb,text,uuid)'::regprocedure,'public.flexexa_revoke_api_client_identity(uuid,jsonb,text,uuid)'::regprocedure) and not prosecdef),2::bigint,'public entry points are invokers');
set local role authenticated;
select pg_temp.claims(1,101,'{"aal":"aal1"}');
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','MFA required even for tenant administrator');
select pg_temp.claims(1,101,'{"session_id":null}');
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','missing live session denied');
select pg_temp.claims(1,102);
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','other user session denied');
select pg_temp.claims(2,102);
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','viewer denied');
select pg_temp.claims(1,101,'{"role":"service_role"}');
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','privileged key claim is not admin session');
select pg_temp.claims();
select throws_ok($$select public.flexexa_enroll_api_client_identity(pg_temp.iid(21),'{}','cross',pg_temp.iid(900))$$,'42501','PERMISSION_DENIED','different tenant denied');
select throws_ok($$select pg_temp.enroll('{"environment":"production"}')$$,'42501','PERMISSION_DENIED','attestation binds environment');
select throws_ok($$select pg_temp.enroll(jsonb_build_object('auth_user_id',pg_temp.iid(11)))$$,'42501','PERMISSION_DENIED','unattested subject denied');
select throws_ok($$select pg_temp.enroll(jsonb_build_object('auth_user_id',pg_temp.iid(1)))$$,'42501','PERMISSION_DENIED','self enrollment denied');
select throws_ok($$select pg_temp.enroll('{"secret":"invalid"}')$$,'P0001','VALIDATION_ERROR','credentials rejected as input');
select throws_ok($$select pg_temp.enroll('{"environment":null}')$$,'P0001','VALIDATION_ERROR','missing environment denied');
select throws_ok($$select pg_temp.enroll('{}',E'bad\n')$$,'P0001','VALIDATION_ERROR','newline idempotency key denied');
reset role;
update auth.users set raw_user_meta_data=raw_app_meta_data,raw_app_meta_data='{}' where id=pg_temp.iid(10);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','editable metadata cannot attest');
reset role;
update auth.users set raw_app_meta_data=raw_user_meta_data,raw_user_meta_data='{}' where id=pg_temp.iid(10);
insert into public.memberships(id,tenant_id,user_id) values(pg_temp.iid(33),pg_temp.iid(20),pg_temp.iid(10));
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','existing human account denied');
reset role;
delete from public.memberships where id=pg_temp.iid(33);
insert into auth.sessions(id,user_id) values(pg_temp.iid(110),pg_temp.iid(10));
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','existing session denied');
reset role;
delete from auth.sessions where id=pg_temp.iid(110);
update auth.users set banned_until=now()+interval '1 hour' where id=pg_temp.iid(10);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','banned target denied');
reset role;
update auth.users set banned_until=null where id=pg_temp.iid(10);
update auth.users set deleted_at=now() where id=pg_temp.iid(10);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','deleted target denied');
reset role;
update auth.users set deleted_at=null where id=pg_temp.iid(10);
update auth.users set is_anonymous=true where id=pg_temp.iid(10);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','anonymous target denied');
reset role;
update auth.users set is_anonymous=false where id=pg_temp.iid(10);
update auth.users set banned_until=now()+interval '1 hour' where id=pg_temp.iid(1);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','banned administrator denied');
reset role;
update auth.users set banned_until=null where id=pg_temp.iid(1);
update auth.sessions set not_after=now()-interval '1 second' where id=pg_temp.iid(101);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','expired administrator session denied');
reset role;
update auth.sessions set not_after=now()+interval '1 hour' where id=pg_temp.iid(101);
update public.api_clients set status='suspended' where id=pg_temp.iid(40);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'P0001','INVALID_STATE_TRANSITION','invalid client status denied');
reset role;
update public.api_clients set status='active' where id=pg_temp.iid(40);
update public.api_clients set client_type='public' where id=pg_temp.iid(40);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'P0001','INVALID_STATE_TRANSITION','invalid client client_type denied');
reset role;
update public.api_clients set client_type='confidential' where id=pg_temp.iid(40);
update public.api_clients set expires_at=null where id=pg_temp.iid(40);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'P0001','INVALID_STATE_TRANSITION','invalid client expires_at denied');
reset role;
update public.api_clients set expires_at=now()+interval '1 hour' where id=pg_temp.iid(40);
set local role authenticated;
insert into identity_results values('enroll',pg_temp.enroll());
select is((select body->>'status' from identity_results where name='enroll'),'enrolled','enrollment returns canonical receipt');
select is(pg_temp.enroll('{}','enroll-1',pg_temp.iid(902)),(select body from identity_results where name='enroll'),'replay retains original receipt and correlation');
select throws_ok($$select pg_temp.enroll('{"environment":"production"}')$$,'P0001','IDEMPOTENCY_CONFLICT','different payload cannot reuse key');
select throws_ok($$select pg_temp.enroll('{}','duplicate')$$,'P0001','INVALID_STATE_TRANSITION','another key cannot duplicate subject enrollment');
select throws_ok($$select pg_temp.revoke('{"environment":"production"}')$$,'P0001','TENANT_MISMATCH','revocation cannot cross environment');
select throws_ok($$select pg_temp.revoke('{"reason_code":"anything"}')$$,'P0001','VALIDATION_ERROR','unknown reason rejected');
select throws_ok($$select * from private.flexexa_machine_principals$$,'42501',null,'private binding is not browser-readable');
reset role;
select is((select valid_until from private.flexexa_machine_principals where auth_user_id=pg_temp.iid(10)),(select expires_at from public.api_clients where id=pg_temp.iid(40)),'binding cannot outlive client enrollment expiry');
select is((select count(*) from public.api_client_permissions where tenant_id=pg_temp.iid(20)),0::bigint,'enrollment grants no permissions');
select is((select count(*) from public.idempotency_records where tenant_id=pg_temp.iid(20)),1::bigint,'failed operations leave no extra receipt');
update public.memberships set status='suspended' where id=pg_temp.iid(31);
set local role authenticated;
select throws_ok($$select pg_temp.enroll()$$,'42501','PERMISSION_DENIED','replay rechecks current authorization');
reset role;
update public.memberships set status='active' where id=pg_temp.iid(31);
insert into auth.sessions(id,user_id) values(pg_temp.iid(110),pg_temp.iid(10));
insert into public.api_client_permissions(tenant_id,api_client_id,permission_id,condition_json)
 select pg_temp.iid(20),pg_temp.iid(40),id,'{"environment":"sandbox"}' from public.permissions where permission_key='integrations.read';
set local role authenticated;
select pg_temp.claims(10,110,'{"aal":"aal1"}');
select ok(public.flexexa_machine_has_permission(pg_temp.iid(20),'integrations.read','sandbox'),'separately granted machine becomes authorized');
select throws_ok($$select pg_temp.revoke()$$,'42501','PERMISSION_DENIED','machine cannot administer itself');
select pg_temp.claims();
insert into identity_results values('revoke',pg_temp.revoke());
select is(pg_temp.revoke('{}','revoke-1',pg_temp.iid(903)),(select body from identity_results where name='revoke'),'revocation replay preserves historical receipt');
select throws_ok($$select pg_temp.revoke('{}','duplicate-revoke')$$,'P0001','INVALID_STATE_TRANSITION','terminal revocation cannot repeat under another key');
select throws_ok($$select pg_temp.enroll('{}','reenroll')$$,'42501','PERMISSION_DENIED','revoked identity with a preexisting session cannot re-enrolls');
select pg_temp.claims(10,110,'{"aal":"aal1"}');
select ok(not public.flexexa_machine_has_permission(pg_temp.iid(20),'integrations.read','sandbox'),'same live session loses machine authorization after revocation');
reset role;
select is((select count(*) from public.audit_events where tenant_id=pg_temp.iid(20)),2::bigint,'one audit per successful operation');
select is((select count(*) from public.outbox_events where tenant_id=pg_temp.iid(20)),2::bigint,'one outbox per successful operation');
select is((select count(*) from public.idempotency_records where tenant_id=pg_temp.iid(20) and status='completed'),2::bigint,'no unfinished receipts');
select is((select status from public.api_clients where id=pg_temp.iid(40)),'active','revocation does not change other identities of canonical client');
select * from finish();
rollback;
