begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select is(private.flexexa_core_v1_country_defaults(),'{"country_code":"SE","timezone":"Europe/Stockholm","currency":"SEK","locale":"sv-SE"}'::jsonb,'V1 defaults preserve prior values');
select is((select provolatile::text from pg_proc where oid='private.flexexa_core_v1_country_defaults()'::regprocedure),'i','metadata helper is immutable');
select ok((select not prosecdef from pg_proc where oid='private.flexexa_core_v1_country_defaults()'::regprocedure),'metadata does not elevate privileges');
select ok(not has_function_privilege('anon','private.flexexa_core_v1_country_defaults()','execute'),'anonymous callers have no execution grant');
select ok(has_function_privilege('authenticated','private.flexexa_core_v1_country_defaults()','execute'),'authenticated column defaults remain executable');
select ok(has_function_privilege('service_role','private.flexexa_core_v1_country_defaults()','execute'),'backend column defaults retain metadata access without new write grants');
select is((select count(*)::integer from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum where n.nspname='public' and c.relname in ('organizations','tenants','customers','sites') and pg_get_expr(d.adbin,d.adrelid) like '%flexexa_core_v1_country_defaults()%'),9,'all nine existing column defaults use versioned metadata');
create function pg_temp.fid(n int) returns uuid language sql immutable as $$ select ('cf300000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
insert into public.organizations(id,name,slug) values(pg_temp.fid(1),'Country fixture','country-fixture');
insert into public.tenants(id,organization_id,name,slug) values(pg_temp.fid(2),pg_temp.fid(1),'Country fixture','country-fixture');
insert into public.customers(id,tenant_id,customer_type,display_name) values(pg_temp.fid(3),pg_temp.fid(2),'person','Country fixture');
insert into public.sites(id,tenant_id,customer_id,name) values(pg_temp.fid(4),pg_temp.fid(2),pg_temp.fid(3),'Country fixture');
select is((select country_code||'|'||timezone||'|'||currency from public.organizations where id=pg_temp.fid(1)),'SE|Europe/Stockholm|SEK','organization inserts retain defaults');
select is((select country_code||'|'||timezone from public.tenants where id=pg_temp.fid(2)),'SE|Europe/Stockholm','tenant inserts retain defaults');
select is((select locale||'|'||timezone from public.customers where id=pg_temp.fid(3)),'sv-SE|Europe/Stockholm','customer inserts retain defaults');
select is((select country_code||'|'||timezone from public.sites where id=pg_temp.fid(4)),'SE|Europe/Stockholm','site inserts retain defaults');
select is(private.flexexa_normalize_core_input('site',jsonb_build_object('customer_id',pg_temp.fid(3),'name','Home','country_code','NO'))->>'timezone','Europe/Stockholm','historical V1 foreign-country normalization stays compatible');
select is(private.flexexa_normalize_core_input('site',jsonb_build_object('customer_id',pg_temp.fid(3),'name','Home','country_code','NO','timezone','Europe/Oslo'))->>'timezone','Europe/Oslo','explicit foreign timezone remains supported');
select * from finish();
rollback;
