begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create function pg_temp.pid(n int) returns uuid language sql immutable as $$select ('be350000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.claims(n int,extra jsonb default '{}') returns text language sql as $$
 select set_config('request.jwt.claims',(jsonb_build_object('sub',pg_temp.pid(n),'session_id',pg_temp.pid(n+100),'role','authenticated','aal','aal2')||extra)::text,true)
$$;
insert into auth.users(id,is_anonymous) select pg_temp.pid(n),false from generate_series(1,4)n;
insert into auth.sessions(id,user_id) select pg_temp.pid(n+100),pg_temp.pid(n) from generate_series(1,4)n;
insert into public.platform_memberships(id,user_id) values(pg_temp.pid(11),pg_temp.pid(1)),(pg_temp.pid(12),pg_temp.pid(2));
insert into public.platform_membership_roles(platform_membership_id,role_id)
 select pm.id,r.id from public.platform_memberships pm cross join public.roles r where pm.id in(pg_temp.pid(11),pg_temp.pid(12)) and r.scope_type='platform' and r.role_key='platform_admin';
insert into public.organizations(id,name,slug) values(pg_temp.pid(30),'Policies','policy-tests');
insert into public.tenants(id,organization_id,name,slug) values(pg_temp.pid(20),pg_temp.pid(30),'A','policy-a'),(pg_temp.pid(21),pg_temp.pid(30),'B','policy-b');
insert into public.memberships(id,tenant_id,user_id) values(pg_temp.pid(41),pg_temp.pid(20),pg_temp.pid(3)),(pg_temp.pid(42),pg_temp.pid(21),pg_temp.pid(4));
insert into public.membership_roles(tenant_id,membership_id,role_id)
 select m.tenant_id,m.id,r.id from public.memberships m join public.roles r on r.tenant_id=m.tenant_id and r.role_key='tenant_admin' where m.id in(pg_temp.pid(41),pg_temp.pid(42));
create temp table policies(name text primary key,body jsonb);
grant all on policies to authenticated;
create function pg_temp.payload(k text default 'policy.test') returns jsonb language sql as $$
 select jsonb_build_object('policy_key',k,'name','Test policy','valid_from','2026-01-01T00:00:00.000Z','valid_until','2099-01-01T00:00:00.000Z',
 'tenants',jsonb_build_array(pg_temp.pid(20)),'rules','[{"rule_key":"power.test","expression":{"minimum_kw":0,"maximum_kw":7,"deny_reasons":[]},"tests":[{"name":"inside","requested_kw":5,"expected_allowed":true},{"name":"outside","requested_kw":8,"expected_allowed":false}]}]'::jsonb)
$$;
create function pg_temp.version(n text default 'first') returns jsonb language sql as $$select jsonb_build_object('policy_set_version_id',body->'policy_set_version_id') from policies where name=n$$;
select ok(not has_function_privilege('anon','public.flexexa_create_policy_set_version(jsonb,text,uuid)','EXECUTE'),'anon cannot author');
select ok(not has_function_privilege('service_role','public.flexexa_publish_policy_set_version(jsonb,text,uuid)','EXECUTE'),'universal key cannot publish');
select ok(not has_function_privilege('authenticated','private.flexexa_assert_policy_admin()','EXECUTE'),'assertion helper private');
select ok(not has_table_privilege('authenticated','public.policy_set_versions','UPDATE'),'direct version mutation forbidden');
select ok(not has_table_privilege('service_role','public.rule_versions','INSERT'),'service key has no direct authoring grant');
select ok(not has_table_privilege('authenticated','private.flexexa_policy_test_runs','INSERT'),'test evidence cannot be forged');
select is((select count(*) from pg_proc where oid in('public.flexexa_create_policy_set_version(jsonb,text,uuid)'::regprocedure,'public.flexexa_publish_policy_set_version(jsonb,text,uuid)'::regprocedure) and not prosecdef),2::bigint,'public contracts are invokers');
set local role authenticated;
select pg_temp.claims(3);
select throws_ok($$select public.flexexa_create_policy_set_version(pg_temp.payload(),'create',pg_temp.pid(900))$$,'42501','PERMISSION_DENIED','tenant admin cannot create global policy');
select pg_temp.claims(1,'{"aal":"aal1"}');
select throws_ok($$select public.flexexa_create_policy_set_version(pg_temp.payload(),'create',pg_temp.pid(900))$$,'42501','PERMISSION_DENIED','MFA required');
select pg_temp.claims(1,'{"session_id":"be350000-0000-4000-8000-000000000102"}');
select throws_ok($$select public.flexexa_create_policy_set_version(pg_temp.payload(),'create',pg_temp.pid(900))$$,'42501','PERMISSION_DENIED','session ownership required');
select pg_temp.claims(1);
select throws_ok($$select public.flexexa_create_policy_set_version(jsonb_set(pg_temp.payload(),'{rules,0,expression}','[]'),'bad',pg_temp.pid(900))$$,'P0001','VALIDATION_ERROR','array expression rejected');
select throws_ok($$select public.flexexa_create_policy_set_version(jsonb_set(pg_temp.payload(),'{rules,0,expression,maximum_kw}','"7"'),'bad',pg_temp.pid(900))$$,'P0001','VALIDATION_ERROR','numeric strings rejected');
select throws_ok($$select public.flexexa_create_policy_set_version(jsonb_set(pg_temp.payload(),'{valid_from}','"2026-02-30T00:00:00.000Z"'),'bad',pg_temp.pid(900))$$,'P0001','VALIDATION_ERROR','impossible instant rejected');
select throws_ok($$select public.flexexa_create_policy_set_version(pg_temp.payload()||'{"sql":"select 1"}','bad',pg_temp.pid(900))$$,'P0001','VALIDATION_ERROR','executable/unknown fields rejected');
insert into policies values('first',public.flexexa_create_policy_set_version(pg_temp.payload(),'create',pg_temp.pid(900)));
select is((select body->>'status' from policies where name='first'),'draft','authoring creates draft');
select is(public.flexexa_create_policy_set_version(pg_temp.payload(),'create',pg_temp.pid(901)),(select body from policies where name='first'),'replay returns original receipt/correlation');
select throws_ok($$select public.flexexa_create_policy_set_version(pg_temp.payload('changed'),'create',pg_temp.pid(900))$$,'P0001','IDEMPOTENCY_CONFLICT','changed request cannot reuse receipt');
select throws_ok($$select public.flexexa_publish_policy_set_version(pg_temp.version(),'publish',pg_temp.pid(900))$$,'P0001','POLICY_DENIED','draft cannot publish');
select is(public.flexexa_test_policy_set_version(pg_temp.version(),'test',pg_temp.pid(900))->>'passed','true','stored expected cases pass');
select pg_temp.claims(2);
select throws_ok($$select public.flexexa_approve_policy_set_version(pg_temp.version(),'approve',pg_temp.pid(900))$$,'P0001','POLICY_DENIED','approval requires shadow evidence');
select pg_temp.claims(1);
select is(public.flexexa_shadow_policy_set_version(pg_temp.version()||'{"observations":[{"requested_kw":8,"expected_allowed":true}]}','bad-shadow',pg_temp.pid(900))->>'passed','false','wrong shadow expectation fails');
select pg_temp.claims(2);
select throws_ok($$select public.flexexa_approve_policy_set_version(pg_temp.version(),'approve',pg_temp.pid(900))$$,'P0001','POLICY_DENIED','failed shadow blocks approval');
select pg_temp.claims(1);
select is(public.flexexa_shadow_policy_set_version(pg_temp.version()||'{"observations":[{"requested_kw":7,"expected_allowed":true},{"requested_kw":8,"expected_allowed":false}]}','shadow',pg_temp.pid(900))->>'passed','true','sandbox shadow records actual intersection');
select throws_ok($$select public.flexexa_approve_policy_set_version(pg_temp.version(),'self-approve',pg_temp.pid(900))$$,'P0001','POLICY_DENIED','author cannot self approve');
select pg_temp.claims(2);
select is(public.flexexa_approve_policy_set_version(pg_temp.version(),'approve',pg_temp.pid(900))->>'status','approved','independent admin approves');
select is(public.flexexa_publish_policy_set_version(pg_temp.version(),'publish',pg_temp.pid(900))->>'status','published','approved policy publishes');
select is(public.flexexa_publish_policy_set_version(pg_temp.version(),'publish',pg_temp.pid(900))->>'status','published','publication replay idempotent');
select is((select status from public.tenant_policy_readiness where policy_set_version_id=(pg_temp.version()->>'policy_set_version_id')::uuid),'pending','publication creates fresh pending readiness');
select lives_ok($$select public.flexexa_evaluate_tenant_policy_readiness(pg_temp.version(),'readiness',pg_temp.pid(900))$$,'current version evaluated');
select is((select status from public.tenant_policy_readiness where policy_set_version_id=(pg_temp.version()->>'policy_set_version_id')::uuid),'blocked','sandbox never pretends production ready');
select is((select blocking_reasons_json from public.tenant_policy_readiness where policy_set_version_id=(pg_temp.version()->>'policy_set_version_id')::uuid),'["SANDBOX_ONLY"]'::jsonb,'explicit sandbox blocker');
reset role;
select is((select count(*) from public.outbox_events where payload_json->>'policy_set_version_id'=pg_temp.version()->>'policy_set_version_id'),1::bigint,'one event despite replay');
select is((select payload_json->>'environment' from public.outbox_events where payload_json->>'policy_set_version_id'=pg_temp.version()->>'policy_set_version_id'),'sandbox','outbox cannot cross environments');
select throws_ok($$update public.policy_set_versions set checksum=repeat('a',64) where id=(pg_temp.version()->>'policy_set_version_id')::uuid$$,'23514','RULE_VERSION_IMMUTABLE','published content immutable even to owner');
select throws_ok($$delete from public.rule_test_cases where rule_version_id in(select rule_version_id from public.policy_set_rule_versions where policy_set_version_id=(pg_temp.version()->>'policy_set_version_id')::uuid)$$,'23514','RULE_VERSION_IMMUTABLE','published evidence immutable');
select throws_ok($$insert into public.policy_set_rule_versions(policy_set_version_id,rule_version_id,priority) select policy_set_version_id,rule_version_id,99 from public.policy_set_rule_versions where policy_set_version_id=(pg_temp.version()->>'policy_set_version_id')::uuid$$,'23514','RULE_VERSION_IMMUTABLE','published membership frozen');
select throws_ok($$insert into public.idempotency_records(actor_type,actor_id,operation_key,idempotency_key,request_hash,correlation_id) values('user',pg_temp.pid(1),'fixture','no-tenant',repeat('a',64),pg_temp.pid(900))$$,'23514',null,'default tenant receipt still requires tenant');
select throws_ok($$insert into public.audit_events(scope_type,actor_type,actor_id,action,resource_type,resource_id,correlation_id,idempotency_record_id) select 'platform','user',pg_temp.pid(1),'fixture','fixture',pg_temp.pid(900),pg_temp.pid(900),id from public.idempotency_records where scope_type='tenant' and tenant_id=pg_temp.pid(20) limit 1$$,'23503',null,'platform audit cannot borrow tenant receipt');
set local role authenticated;
select pg_temp.claims(3);
select is((select count(*) from public.policy_set_versions),0::bigint,'tenant admin cannot inspect global registry');
select is((select count(*) from public.audit_events where scope_type='platform'),0::bigint,'platform audit hidden from tenant admin');
select is((select count(*) from public.tenant_policy_readiness),1::bigint,'own tenant sees own readiness');
select pg_temp.claims(4);
select is((select count(*) from public.tenant_policy_readiness),0::bigint,'other tenant sees no readiness');
select pg_temp.claims(1);
insert into policies values('second',public.flexexa_create_policy_set_version(pg_temp.payload(),'create2',pg_temp.pid(900)));
select is(public.flexexa_test_policy_set_version(pg_temp.version('second'),'test2',pg_temp.pid(900))->>'passed','true','next version tests');
select is(public.flexexa_shadow_policy_set_version(pg_temp.version('second')||'{"observations":[{"requested_kw":5,"expected_allowed":true}]}','shadow2',pg_temp.pid(900))->>'passed','true','next version shadow');
select pg_temp.claims(2);
select lives_ok($$select public.flexexa_approve_policy_set_version(pg_temp.version('second'),'approve2',pg_temp.pid(900))$$,'next version approved independently');
select lives_ok($$select public.flexexa_publish_policy_set_version(pg_temp.version('second'),'publish2',pg_temp.pid(900))$$,'next version published');
select is((select status from public.tenant_policy_readiness where policy_set_version_id=(pg_temp.version()->>'policy_set_version_id')::uuid),'superseded','old readiness invalidated');
select is((select status from public.tenant_policy_readiness where policy_set_version_id=(pg_temp.version('second')->>'policy_set_version_id')::uuid),'pending','new version does not inherit prior readiness');
select throws_ok($$select public.flexexa_evaluate_tenant_policy_readiness(pg_temp.version(),'stale-readiness',pg_temp.pid(900))$$,'P0001','POLICY_DENIED','old version cannot regain current readiness');
reset role;
update auth.sessions set not_after=clock_timestamp()-interval '1 second' where id=pg_temp.pid(102);
set local role authenticated;
select throws_ok($$select public.flexexa_publish_policy_set_version(pg_temp.version('second'),'publish2',pg_temp.pid(900))$$,'42501','PERMISSION_DENIED','expired session cannot replay successful publication');
select is((select count(*) from public.policy_set_versions),0::bigint,'expired session cannot read registry');
reset role;
select * from finish();
rollback;
