definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.json
listeners.tcp.default = 5672
loopback_users.guest = true
log.console = true
log.console.level = warning
log.file = false
vm_memory_high_watermark.absolute = 256MiB
disk_free_limit.absolute = 64MiB
